[build]
  publish = "."
  functions = "netlify/functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

# Yeh naya part add karna hai
[[plugins]]
  package = "@netlify/plugin-functions-install-core"
